# Generated by Django 4.0.3 on 2022-03-23 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_crypto_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2000-02-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNo',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.RegexValidator(message='THIS WILL ONLY ALLOW TEN DIGIT NUMBERS', regex='^[0-9]{10}$')]),
        ),
    ]
