# Generated by Django 4.0.3 on 2022-04-01 01:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_crypto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='cumulativeAmount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currRate',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='sold',
        ),
        migrations.AddField(
            model_name='wallet',
            name='buyRate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='cryptoRate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 21, 23, 54, 407309)),
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='available',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNo', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='THIS WILL ONLY ALLOW TWELVE DIGIT NUMBERS', regex='^[0-9]{12}$')])),
                ('expiryDate', models.DateField()),
                ('CVV', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='THIS WILL ONLY ALLOW THREE DIGIT NUMBERS', regex='^[0-9]{3}$')])),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.user')),
            ],
        ),
    ]
