# Generated by Django 4.0.3 on 2022-04-01 18:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_alter_crypto_description_alter_wallet_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cardNo',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='THIS WILL ONLY ALLOW TWELVE DIGIT NUMBERS', regex='^[0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 14, 59, 23, 165201)),
        ),
    ]
