# Generated by Django 4.0.3 on 2022-04-01 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_alter_paymentinfo_cardno_alter_wallet_paymentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='cardHolderName',
            field=models.CharField(default='Neel', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 17, 51, 52, 418587)),
        ),
    ]
