# Generated by Django 4.0.3 on 2022-04-03 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_paymentinfo_cardholdername_alter_wallet_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 20, 51, 19, 875224)),
        ),
    ]
