# Generated by Django 4.0.3 on 2022-04-04 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_alter_wallet_paymentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='buyRate',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 3, 21, 51, 10, 888678)),
        ),
    ]
