# Generated by Django 4.0.3 on 2022-04-04 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_rename_buyrate_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 0, 17, 48, 588648)),
        ),
        migrations.CreateModel(
            name='Wallet2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoRate', models.FloatField()),
                ('amount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1)),
                ('paymentDate', models.DateField(default=datetime.datetime(2022, 4, 4, 0, 17, 48, 588648))),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.user')),
            ],
        ),
    ]
