# Generated by Django 4.0.3 on 2022-04-04 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_alter_wallet_paymentdate_wallet2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 4, 21, 17, 660887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wallet2',
            name='paymentDate',
            field=models.DateField(default=datetime.datetime(2022, 4, 4, 4, 21, 17, 660887, tzinfo=utc)),
        ),
    ]
