# Generated by Django 4.0.3 on 2022-04-04 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0017_user_walletbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='CVV',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='THIS WILL ONLY ALLOW 3 DIGIT NUMBERS', regex='^[0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='cardNo',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='THIS WILL ONLY ALLOW 16 DIGIT NUMBERS', regex='^[0-9]{16}$')]),
        ),
    ]
