# Generated by Django 4.0.3 on 2022-04-04 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0018_alter_paymentinfo_cvv_alter_paymentinfo_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNo',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='THIS WILL ONLY ALLOW TEN DIGIT NUMBERS', regex='^[0-9]{10}$')]),
        ),
    ]
